# Generated by Django 4.2.16 on 2024-10-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinateur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='coordinateur',
            name='prenom',
        ),
    ]
