# Generated by Django 4.2.16 on 2024-10-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_coordinateur_nom_remove_coordinateur_prenom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='nom_entreprise',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='adresse',
        ),
    ]
