version: '3'

services:
  jenkins:
    build: .
    container_name: jenkins_test
    ports:
      - "8080:8080"  # Port pour accéder à l'interface Jenkins
      - "50000:50000" # Port pour les agents Jenkins (si besoin)
    volumes:
      - jenkins_home:/var/jenkins_home  # Volume persistant pour sauvegarder les données
      - /var/run/docker.sock:/var/run/docker.sock # Permet à Jenkins d'exécuter Docker
    environment:
      - JENKINS_OPTS=--prefix=/jenkins

volumes:
  jenkins_home:
